//! Citation types — where a model's claim came from in a source document.

use serde::{Deserialize, Serialize};

/// The span within a source that a citation points at.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
#[allow(missing_docs)] // Index/start/end fields are self-describing ranges.
pub enum CitationLocation {
    /// A character range within a document.
    DocumentChar {
        document_index: usize,
        start: usize,
        end: usize,
    },
    /// A chunk range within a document.
    DocumentChunk {
        document_index: usize,
        start: usize,
        end: usize,
    },
    /// A page range within a document.
    DocumentPage {
        document_index: usize,
        start: usize,
        end: usize,
    },
    /// A span within a search result content block.
    SearchResult {
        search_result_index: usize,
        start: usize,
        end: usize,
    },
    /// A page found via web search.
    Web {
        #[serde(skip_serializing_if = "Option::is_none")]
        url: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        domain: Option<String>,
    },
}

/// A quoted excerpt, either from the source or as generated by the model.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CitationContent {
    /// The quoted text.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

/// A single citation linking generated content back to a source.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Citation {
    /// Where in the source this citation points.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<CitationLocation>,
    /// The excerpt from the source document.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub source_content: Vec<CitationContent>,
    /// Title of the cited source.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// A content block carrying generated text together with its citations.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CitationsContentBlock {
    /// The generated text these citations support.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub content: Vec<CitationContent>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    /// The sources supporting that content.
    pub citations: Vec<Citation>,
}
